### ISSUE TITLE
Getting error in saavn_downloader.py

### ISSUE THREAD

**Issue by amail101** [dedshit/jio-saavu-downloader#1]
```

 Enter link : https://www.jiosaavn.com/song/o-saathi-humsafar/OiEDR0cBcwY 

 Enter bitrate( default:256 ) : 256
Traceback (most recent call last):
  File "C:/Users/amail101/Music/jio-saavu-downloader-master/Saavn/Saavn_Downloader.py", line 27, in <module>
    qq = s.find_all('div', id="header")[0]
IndexError: list index out of range

Process finished with exit code 1

```

**Comment by dedshit** [comment]
Thanls

> ```
> 
>  Enter link : https://www.jiosaavn.com/song/o-saathi-humsafar/OiEDR0cBcwY 
> 
>  Enter bitrate( default:256 ) : 256
> Traceback (most recent call last):
>   File "C:/Users/amail101/Music/jio-saavu-downloader-master/Saavn/Saavn_Downloader.py", line 27, in <module>
>     qq = s.find_all('div', id="header")[0]
> IndexError: list index out of range
> 
> Process finished with exit code 1
> ```


Thanks for identifying that , i will fix this soon 👍

**Comment by dedshit** [comment]
> ```
> 
>  Enter link : https://www.jiosaavn.com/song/o-saathi-humsafar/OiEDR0cBcwY 
> 
>  Enter bitrate( default:256 ) : 256
> Traceback (most recent call last):
>   File "C:/Users/amail101/Music/jio-saavu-downloader-master/Saavn/Saavn_Downloader.py", line 27, in <module>
>     qq = s.find_all('div', id="header")[0]
> IndexError: list index out of range
> 
> Process finished with exit code 1
> ```


Fixed Just clone latest one 👇👇👇

https://github.com/dedshit/jio-saavu-downloader/
